### ISSUE TITLE
Honors

### ISSUE THREAD

**Issue by mrquincle** [NordicSemiconductor/nRF51-ble-bcast-mesh#1]
Currently the `README` file states that this code is written as part of a master thesis project. I like to know who I can mention and wrote this great piece of code!

Honor to whom honor is due. :-)

**Comment by trond-snekvik** [comment]
Hi, thank you!
That would be Trond Einar Snekvik, department of Engineering Cybernetics of NTNU :-)

I'll see if I can add it to the readme for the next version.
