### ISSUE TITLE
adv_int_ms as uint8_t Typo?

### ISSUE THREAD

**Issue by olskyy** [NordicSemiconductor/nRF51-ble-bcast-mesh#11]
the adv_int_ms is defined as uint8_t, shouldnt be uint32_t? :-)

> adv_int_ms The minimum adv_interval for nodes in the network in millis. Must be between 5 and 60000.

**Comment by trond-snekvik** [comment]
You are correct. We'll change it asap :)

**Comment by olskyy** [comment]
Thanks! :)

**Comment by trond-snekvik** [comment]
This was fixed as commit 4d5ba91c13326614c48f4cbe8259c552bc881b09 in release v0.6.2. 
Note that the commit message incorrectly references this as #9.
