### ISSUE TITLE
Advertisement address is origin of value update, not latest hop address

### ISSUE THREAD

**Issue by pehrnord** [NordicSemiconductor/nRF51-ble-bcast-mesh#117]
There seems to have been a regression (or undocumented change?) of the advertisement address from v0.8.2 to v0.8.3. From what I can tell, in v0.8.3, the advertisement address field contains the address of the originator of the value update and not the latest hop address

**Comment by trond-snekvik** [comment]
Fixed as of 0.8.4. Feel free to reopen if you experience any further issues.
