### ISSUE TITLE
TX_Power not consistent

### ISSUE THREAD

**Issue by olsky** [NordicSemiconductor/nRF51-ble-bcast-mesh#130]
The new set/init with tx_power interface has no effect.

Current flow:
- radio_init is called from transport_control.c TX_power is set to 0dBm
- later setup_event is called, there TX_power is set with event's field

Somehow it does not affect the power.

Could it be that an extra param needed in radio_init function with the tx_power? Thus the power will be constant?

**Comment by trond-snekvik** [comment]
Hi Olsky, looks like this one slipped through the cracks, sorry about that.

I'll take a look at it for the next release. I have a couple of additional fixes coming in September.

**Comment by olsky** [comment]
Hi Trond, thank you for note!

Looking forward for new commits :+1:

**Comment by downwith** [comment]
Just stumbled across this issue on my own, too.  Can confirm.  The event didn't seem to be having an effect for me at all.  Just the radio_init hardcoded value.

**Comment by trond-snekvik** [comment]
Fixed in 0.8.7.
