### ISSUE TITLE
Internal event queue size

### ISSUE THREAD

**Issue by downwith** [NordicSemiconductor/nRF51-ble-bcast-mesh#134]
`RBC_MESH_INTERNAL_EVENT_QUEUE_LENGTH` in rbc_mesh.h does not appear to be linked to the size of the event queue.  I'm guessing `ASYNC_EVENT_FIFO_QUEUE_SIZE` in event_handler.c should be replaced by this.  Am I correct?

**Comment by trond-snekvik** [comment]
I believe you're correct, yes.

**Comment by trond-snekvik** [comment]
Fixed in 0.8.7
