### ISSUE TITLE
documents for Bandwidth_test example

### ISSUE THREAD

**Issue by rick1082** [NordicSemiconductor/nRF51-ble-bcast-mesh#144]
Hi,

Is there any documents or guides for nRF51-ble-bcast-mesh/nRF51/examples/Bandwidth_test ?
For now, the description of the Bandwidth_test example still remains in BLE_Gateway,
It's a little hard to figure out how to use this example to perform bandwidth test.

Thanks :)

**Comment by baruaanomadarshishuvro** [comment]
Hi,
read me doc has been updated for the bandwidth test .

Thanks :)

**Comment by rick1082** [comment]
Thank you @baruaanomadarshishuvro,  According to the document, there still needs a python test script. Would Nordic provide the example of the python test script ? Really thanks :D

**Comment by baruaanomadarshishuvro** [comment]
Hi, 
i have added a sample python script(Bandwidth_Test.py) to calculate the bandwidth and also updated the read me doc accordingly.

Thanks :)

**Comment by rick1082** [comment]
So many thanks, @baruaanomadarshishuvro 
Really appreciate : D
