### ISSUE TITLE
uint32_t variables assigned to false in timeslot_handler

### ISSUE THREAD

**Issue by AlexDM0** [NordicSemiconductor/nRF51-ble-bcast-mesh#15]
Hi Trond,

There are two variables in timeslot_handler.c defined as uint32_t and assigned a boolean value. Is this a bug?

https://github.com/NordicSemiconductor/nRF51-ble-bcast-mesh/blob/master/nRF51/rbc_mesh/src/timeslot_handler.c#L117

Regards,

Alex

**Comment by trond-snekvik** [comment]
Hah, yes, sort of. They are both meant to act as booleans, and are assigned and as such. There isn't any faulty behavior because of this, but it _is_ a bit misleading. I'll put it on the fix-list.

Thanks,
Trond

**Comment by AlexDM0** [comment]
Every bit counts with 16kb ram ;)

Thanks!

**Comment by trond-snekvik** [comment]
That's true :)
