### ISSUE TITLE
Mesh Metadata Characteristic data length

### ISSUE THREAD

**Issue by eggerdo** [NordicSemiconductor/nRF51-ble-bcast-mesh#17]
In the document at https://github.com/NordicSemiconductor/nRF51-ble-bcast-mesh/blob/master/docs/how_it_works.adoc#mesh-metadata, the data of the metadata characteristic is defined as a structure of 10 bytes, but in the code, lines 177-179, the data length is set as:

``` cpp
ble_attr.init_len = 9;
ble_attr.init_offs = 0;
ble_attr.max_len = 9;
```

Because of this, the channel is not in the meta data characteristic. Is that a bug or on purpose? If the latter, why so? Shouldn't it rather be

``` cpp
ble_attr.init_len = MESH_MD_CHAR_LEN;
ble_attr.init_offs = 0;
ble_attr.max_len = MESH_MD_CHAR_LEN;
```

**Comment by trond-snekvik** [comment]
Thanks, this has been fixed for v0.6.3
