### ISSUE TITLE
not working example with nRF51422

### ISSUE THREAD

**Issue by MateuszKSS** [NordicSemiconductor/nRF51-ble-bcast-mesh#174]

**Comment by trond-snekvik** [comment]
Hi,

I'm afraid I need some more info to help you.

Which target are you building? serial or not? with button support? 
Which board are you using?
Have you tried connecting a debugger? Is the program running?
Have you tried scanning for it with the [nRF Connect app for Android](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) or something similar for iPhone?

Try compiling and flashing the "nRF51422 xxAC buttons" target. If you have a Development Kit, does it change its LEDs if you press any of its buttons? Are there any LEDs lit when you start up?

**Comment by MateuszKSS** [comment]
Hi,

Thanks for repply.

I just solved this problem.

 

Best regards / Pozdrawiam / Grüße / Un Saludo
Mateusz Miga 

Electronic Designer / Konstruktor Elektronik
Tel: +48 32 32 46 397 

 Stopka <file:///c:\podpis\stopka.jpg> 

  _____
