### ISSUE TITLE
Wrong function name in documentation /docs/integrating_w_SD_apps.adoc

### ISSUE THREAD

**Issue by RemiSaunier** [NordicSemiconductor/nRF51-ble-bcast-mesh#29]
In nRF51-ble-bcast-mesh/docs/integrating_w_SD_apps.adoc, in Step 2: a common SWI0, a change is suggested in app_timer.c: 

> void app_timer_SWI0_IRQHandler(void)

deosn't work, should be:

> void SWI0_IRQHandler(void)

**Comment by trond-snekvik** [comment]
You're quite right. It seems like there's been a mixup between the App Timer in SDK6 and SDK7 when writing this. In SDK6, the function is already named SWI0_IRQHandler, but that changed in SDK7. I'll see if I can rewrite the step to work for both versions of the SDK for the next release. 
Thanks!

**Comment by trond-snekvik** [comment]
No longer relevant as of v0.6.9.
