### ISSUE TITLE
Moving to SD S130?

### ISSUE THREAD

**Issue by olsky** [NordicSemiconductor/nRF51-ble-bcast-mesh#65]
Is there a plan to move to sd s130? 

...reading the v11 changelog "Permanently removed support for SoftDevices S110 and S120" seems the s110 will not be supported anymore...  Can you please comment?

Thanks!

**Comment by daviddedwin** [comment]
The S110 will continue to be supported and bugs will be fixed on it. The SDK 11 however is not supporting the S110 as there is an API change in the S130 vs the S110. The Mesh however will continue to support both S110 and S130. The S110 will be supported in the SDK 10 release line.

Edit: The timeslot API the Mesh uses is not affected by the S130 update so S110 and S130 continue to be supported.

**Comment by olskyy** [comment]
Thank you for the clarification.
