### ISSUE TITLE
thesis information

### ISSUE THREAD

**Issue by vihman** [NordicSemiconductor/nRF51-ble-bcast-mesh#68]
Hello,
I'm currently writing a master thesis about organizational monitoring in Tallinn University of Technology.
Can you please provide pdf or at least author and title of the NTNU thesis of this mesh implementation. Thank you.

**Comment by daviddedwin** [comment]
I think this is best done on the Nordic support portal.[ http://www.nordicsemi.com/eng/Support/Contact-Support-Team ](url) . Please open a case and request your information.
