### ISSUE TITLE
using rbc_mesh_tx_event_set and rbc_mesh_packet_release

### ISSUE THREAD

**Issue by victorpasse** [NordicSemiconductor/nRF51-ble-bcast-mesh#72]
When using rbc_mesh_tx_event_set the pakage will never be un referenced and deleted as the mesh_evt.data is NULL and rbc_mesh_packet_release will not call mesh_packet_ref_count_dec with the correct pointer, I get a fault as mesh_packet_acquire can not find a free slot after sending several packages on the handle with tx event enabled.

**Comment by trond-snekvik** [comment]
Thanks for reporting, I'll see if we can push a fix for it :)

**Comment by olsky** [comment]
:+1: good one!
