### ISSUE TITLE
Undefined Symbol SPI0_IRQHandler

### ISSUE THREAD

**Issue by erinsb** [NordicSemiconductor/nRF51-ble-bcast-mesh#75]
Hi there,

I recently updated to use the most current version of the sdk-8-support branch and I'm running into an issue only when I try to compile the serial file. I get the error: Undefined symbol SPI0_IRQHandler (referred from serial_handler_spi.o). When I run the button or the original target, everything runs just fine, as did the previous version of the project.

**Comment by trond-snekvik** [comment]
Hi,
There seems to be a slight mishap here, sorry!

The IRQ-handler should be `SPI1_TWI1_IRQHandler`.

**Comment by erinsb** [comment]
I wondered if that was the case. It works now!
Thanks!
