### ISSUE TITLE
Strange code in transport_control.c

### ISSUE THREAD

**Issue by victorpasse** [NordicSemiconductor/nRF51-ble-bcast-mesh#80]
int16_t delta = vh_get_version_delta(p_mesh_adv_data->handle, p_mesh_adv_data->version);

This makes no sense, p_mesh_adv_data->handle has nothing to do with the old version.
Is this a mistake or am I confused?

**Comment by victorpasse** [comment]
I would suggest editing vh_get_version_delta such that it takes an handle and a new version as there are some static functions in version handler C file that extracts version from handle that can still be static.

**Comment by trond-snekvik** [comment]
This is a mistake, you're correct. I think the cleanest fix is to add a return-by-pointer argument to the `vh_rx_register(p_mesh_adv_data, timestamp)` call right below it, as it calculates the delta anyway.
