### ISSUE TITLE
Broken link to how the mesh works

### ISSUE THREAD

**Issue by electronut** [NordicSemiconductor/nRF51-ble-bcast-mesh#95]
The following link is broken:

https://github.com/NordicSemiconductor/nRF51-ble-bcast-mesh/blob/docs/how_it_works.adoc

Referring page:

"How the Mesh works"

https://github.com/NordicSemiconductor/nRF51-ble-bcast-mesh

**Comment by trond-snekvik** [comment]
Thanks, looks like we have some fallout from the switch to master.
