### ISSUE TITLE
Break missing in async_event_execute

### ISSUE THREAD

**Issue by victorpasse** [NordicSemiconductor/nRF51-ble-bcast-mesh#98]
Should there not be an break between EVENT_TYPE_PACKET and EVENT_TYPE_SET_FLAG?

**Comment by trond-snekvik** [comment]
[Fixed in 0.8.4](https://github.com/NordicSemiconductor/nRF51-ble-bcast-mesh/blob/master/nRF51/rbc_mesh/src/event_handler.c#L74), thanks :)
